# Generated by Django 5.2.7 on 2025-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Paket')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('destination', models.CharField(max_length=100, verbose_name='Destinasi')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('duration_days', models.IntegerField(verbose_name='Durasi (Hari)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga (Rp)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='Gambar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paket Travel',
                'verbose_name_plural': 'Paket Travel',
                'ordering': ['-created_at'],
            },
        ),
    ]
